security:
    password_hashers:
        App\Entity\Etudiant:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Etudiant
                property: email

    firewalls:
        main:
            provider: app_user_provider
            form_login:
                login_path: signin
                check_path: signin
                enable_csrf: true
                csrf_token_id: authenticate
            logout:
                path: app_logout
                target: /
                enable_csrf: true
                csrf_token_id: logout
